import { CurrencyCode } from "../types/api";

export const CurrencySymbols: Record<CurrencyCode, string> = {
  AED: "د.إ",
  AMD: "֏",
  AUD: "A$",
  AZN: "₼",
  BGN: "лв",
  BHD: ".د.ب",
  BRL: "R$",
  BYN: "Br",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  CZK: "Kč",
  DKK: "kr",
  EUR: "€",
  GBP: "£",
  GEL: "₾",
  HKD: "HK$",
  HUF: "Ft",
  IDR: "Rp",
  ILS: "₪",
  INR: "₹",
  JPY: "¥",
  KGS: "с",
  KRW: "₩",
  KWD: "د.ك",
  KZT: "₸",
  MDL: "L",
  MXN: "Mex$",
  MYR: "RM",
  NOK: "kr",
  NZD: "NZ$",
  PLN: "zł",
  QAR: "ر.ق",
  RON: "lei",
  RUB: "₽",
  SAR: "ر.س",
  SEK: "kr",
  SGD: "S$",
  THB: "฿",
  TJS: "SM",
  TMT: "m",
  TRY: "₺",
  UAH: "₴",
  USD: "$",
  UZS: "soʻm",
  VND: "₫",
  ZAR: "R",
};

export function getCurrencySymbol(code?: CurrencyCode): string {
  if (!code) return "";
  return CurrencySymbols[code] ?? code;
}
